//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BAngularTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTransaction
    {
        public int TransationId { get; set; }
        public Nullable<int> CustomerAccountId { get; set; }
        public Nullable<double> Amount { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public Nullable<int> TransactionTypeId { get; set; }
    
        public virtual tblCustomerAccount tblCustomerAccount { get; set; }
        public virtual tblTransactionType tblTransactionType { get; set; }
    }
}
